# Generated by Django 4.2.3 on 2025-10-02 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_access_technology",
                    models.BooleanField(
                        default=False, help_text="Access to technology/IT services"
                    ),
                ),
                (
                    "can_access_print_design",
                    models.BooleanField(
                        default=False, help_text="Access to print and design services"
                    ),
                ),
                (
                    "primary_department",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("print_design", "Print & Design"),
                            ("master", "Master Access"),
                        ],
                        default="technology",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
