version: '3.4'
services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/python:0-3.11
    network_mode: "host"
    env_file:
      - ../.config/site.env
    volumes:
      - ../:/workspaces/simple-django
