# Generated by Django 4.2.3 on 2025-10-02 02:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bidsheets", "0001_initial"),
        ("printdesign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("technology", "Technology"),
                            ("print_design", "Print & Design"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tech_backlog", "Backlog"),
                            ("tech_in_progress", "In Progress"),
                            ("tech_awaiting_client", "Awaiting Client"),
                            ("tech_testing", "Testing"),
                            ("tech_completed", "Completed"),
                            ("print_design_brief", "Design Brief"),
                            ("print_design_phase", "Design Phase"),
                            ("print_client_approval", "Client Approval"),
                            ("print_production", "Production"),
                            ("print_quality_check", "Quality Check"),
                            ("print_delivered", "Delivered"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "actual_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "billable_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("sla_due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_hours",
                    models.IntegerField(default=24, help_text="SLA in hours"),
                ),
                ("sla_breached", models.BooleanField(default=False)),
                ("sla_breach_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, help_text="0-100"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bid_sheet",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_card",
                        to="bidsheets.bidsheet",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "print_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_project_cards",
                        to="printdesign.printcustomer",
                    ),
                ),
                (
                    "print_estimate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_card",
                        to="printdesign.printestimate",
                    ),
                ),
                (
                    "tech_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_project_cards",
                        to="bidsheets.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Card",
                "verbose_name_plural": "Project Cards",
                "ordering": ["sort_order", "-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                (
                    "vin",
                    models.CharField(blank=True, max_length=17, null=True, unique=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "print_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="printdesign.printcustomer",
                    ),
                ),
                (
                    "tech_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="bidsheets.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["license_plate"],
            },
        ),
        migrations.CreateModel(
            name="VehicleDropOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_drop_off", models.DateTimeField()),
                ("actual_drop_off", models.DateTimeField(blank=True, null=True)),
                ("expected_completion", models.DateTimeField()),
                ("actual_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "drop_off_location",
                    models.CharField(default="Main Shop", max_length=200),
                ),
                ("bay_number", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("dropped_off", "Vehicle Dropped Off"),
                            ("in_progress", "Work In Progress"),
                            ("awaiting_parts", "Awaiting Parts"),
                            ("completed", "Work Completed"),
                            ("ready_pickup", "Ready for Pickup"),
                            ("picked_up", "Picked Up"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("work_description", models.TextField()),
                ("customer_notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("drop_off_contact", models.CharField(blank=True, max_length=100)),
                ("pickup_contact", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_drop_offs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_drop_offs",
                        to="tracking.projectcard",
                    ),
                ),
                (
                    "technician_assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_offs",
                        to="tracking.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Drop-Off",
                "verbose_name_plural": "Vehicle Drop-Offs",
                "ordering": ["-scheduled_drop_off"],
            },
        ),
        migrations.CreateModel(
            name="InstallationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "install_type",
                    models.CharField(
                        choices=[
                            ("onsite", "On-Site Installation"),
                            ("shop", "Shop Installation"),
                            ("mobile", "Mobile Service"),
                            ("delivery", "Delivery Only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("team_dispatched", "Team Dispatched"),
                            ("on_site", "On Site"),
                            ("in_progress", "Installation In Progress"),
                            ("completed", "Installation Complete"),
                            ("client_signoff", "Client Sign-Off"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                (
                    "estimated_duration",
                    models.DurationField(default=datetime.timedelta(seconds=7200)),
                ),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("install_address", models.TextField()),
                ("special_instructions", models.TextField(blank=True)),
                ("equipment_needed", models.TextField(blank=True)),
                ("primary_contact", models.CharField(max_length=100)),
                ("contact_phone", models.CharField(max_length=20)),
                ("backup_contact", models.CharField(blank=True, max_length=100)),
                ("completion_notes", models.TextField(blank=True)),
                ("client_signature", models.CharField(blank=True, max_length=100)),
                ("photos_taken", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="tracking.projectcard",
                    ),
                ),
                (
                    "technician_team",
                    models.ManyToManyField(
                        blank=True,
                        related_name="installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Installation Schedule",
                "verbose_name_plural": "Installation Schedules",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="CardComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("status_change", "Status Change"),
                            ("assignment", "Assignment Change"),
                            ("time_log", "Time Log"),
                            ("file_upload", "File Upload"),
                            ("system", "System Update"),
                        ],
                        default="comment",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "time_spent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("billable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tracking.projectcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CardAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="card_attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tracking.projectcard",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
