# Generated by Django 4.2.3 on 2025-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="current_driver",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_mileage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="department",
            field=models.CharField(
                choices=[
                    ("technology", "Technology"),
                    ("print_design", "Print & Design"),
                    ("shared", "Shared"),
                ],
                default="shared",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="next_service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("maintenance", "In Maintenance"),
                    ("out_of_service", "Out of Service"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("truck", "Truck"),
                    ("van", "Van"),
                    ("car", "Car"),
                    ("trailer", "Trailer"),
                    ("equipment", "Equipment"),
                ],
                default="truck",
                max_length=20,
            ),
        ),
    ]
