repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        name: Validating YAML Files
      - id: end-of-file-fixer
        name: Adding EOF Linebreaks
      - id: trailing-whitespace
        name: Removing Trailing Whitespaces
      - id: check-added-large-files
        name: Large File Check
      - id: check-docstring-first
        name: Ensuring Docstring is at Top
      - id: check-merge-conflict
        name: Merge Conflict String Check
      - id: detect-private-key
        name: Private Keys Check
  - repo: local
    hooks:
      - id: pylint-local
        name: Local PyLint
        entry: pylint
        language: system
        types: [python]
        exclude: &python_excludes migrations/
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=99, --preview]
        name: Black Formatter
        exclude: *python_excludes
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.16
    hooks:
      - id: djlint-django
        name: Linting Django Templates
