# Generated by Django 4.2.3 on 2025-10-02 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                            ("non_profit", "Non-Profit"),
                            ("government", "Government"),
                        ],
                        default="business",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("text", "Text Message"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("tax_exempt", models.BooleanField(default=False)),
                ("tax_exempt_number", models.CharField(blank=True, max_length=50)),
                ("credit_approved", models.BooleanField(default=False)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_customers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Customer",
                "verbose_name_plural": "Print Customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrintEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimate_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Customer"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("in_production", "In Production"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateField(auto_now_add=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("production_start_date", models.DateField(blank=True, null=True)),
                ("estimated_completion_date", models.DateField(blank=True, null=True)),
                ("project_address", models.TextField(blank=True)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_terms", models.CharField(default="Net 30", max_length=100)),
                ("warranty_terms", models.TextField(blank=True)),
                ("delivery_terms", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_estimates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="printdesign.printcustomer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Estimate",
                "verbose_name_plural": "Print Estimates",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="PrintServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Print Service Category",
                "verbose_name_plural": "Print Service Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("business_cards", "Business Cards"),
                            ("brochures", "Brochures"),
                            ("flyers", "Flyers"),
                            ("banners", "Banners"),
                            ("signs", "Signs"),
                            ("vehicle_graphics", "Vehicle Graphics"),
                            ("promotional", "Promotional Items"),
                            ("custom", "Custom Products"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "available_sizes",
                    models.TextField(help_text="List available sizes, one per line"),
                ),
                (
                    "available_papers",
                    models.TextField(
                        help_text="List available paper types, one per line"
                    ),
                ),
                (
                    "available_finishes",
                    models.TextField(help_text="List available finishes, one per line"),
                ),
                (
                    "color_options",
                    models.TextField(help_text="Color options available"),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_notes",
                    models.TextField(
                        blank=True, help_text="Additional pricing information"
                    ),
                ),
                ("min_quantity", models.IntegerField(default=1)),
                ("production_time_days", models.IntegerField(default=1)),
                ("setup_required", models.BooleanField(default=False)),
                ("design_included", models.BooleanField(default=False)),
                ("image", models.ImageField(blank=True, upload_to="product_images/")),
                (
                    "sample_image",
                    models.ImageField(blank=True, upload_to="product_samples/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Sheet",
                "verbose_name_plural": "Product Sheets",
                "ordering": ["product_type", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrintServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("sqft", "Square Foot"),
                            ("linft", "Linear Foot"),
                            ("sheet", "Sheet"),
                            ("hour", "Hour"),
                            ("day", "Day"),
                            ("project", "Project"),
                        ],
                        default="each",
                        max_length=20,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paper_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Paper"),
                            ("premium", "Premium Paper"),
                            ("cardstock", "Cardstock"),
                            ("vinyl", "Vinyl"),
                            ("canvas", "Canvas"),
                            ("fabric", "Fabric"),
                            ("metal", "Metal"),
                            ("acrylic", "Acrylic"),
                            ("foam_board", "Foam Board"),
                            ("coroplast", "Coroplast"),
                            ("banner", "Banner Material"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "finish_type",
                    models.CharField(
                        choices=[
                            ("none", "No Finish"),
                            ("gloss", "Gloss"),
                            ("matte", "Matte"),
                            ("satin", "Satin"),
                            ("uv_coating", "UV Coating"),
                            ("laminated", "Laminated"),
                            ("embossed", "Embossed"),
                            ("foil_stamped", "Foil Stamped"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("min_quantity", models.IntegerField(default=1)),
                ("max_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "setup_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "tier_1_qty",
                    models.IntegerField(
                        default=1, help_text="Quantity for tier 1 pricing"
                    ),
                ),
                (
                    "tier_1_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit for tier 1",
                        max_digits=10,
                    ),
                ),
                (
                    "tier_2_qty",
                    models.IntegerField(
                        blank=True, help_text="Quantity for tier 2 pricing", null=True
                    ),
                ),
                (
                    "tier_2_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tier_3_qty",
                    models.IntegerField(
                        blank=True, help_text="Quantity for tier 3 pricing", null=True
                    ),
                ),
                (
                    "tier_3_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_design", models.BooleanField(default=False)),
                ("production_time_days", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="printdesign.printservicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Service Item",
                "verbose_name_plural": "Print Service Items",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrintEstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_type", models.CharField(default="each", max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, help_text="e.g., 24x36 inches", max_length=100
                    ),
                ),
                ("paper_type", models.CharField(blank=True, max_length=100)),
                ("finish_type", models.CharField(blank=True, max_length=100)),
                (
                    "colors",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 4/4 (full color both sides)",
                        max_length=100,
                    ),
                ),
                (
                    "setup_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("production_notes", models.TextField(blank=True)),
                ("requires_design", models.BooleanField(default=False)),
                (
                    "design_time_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="printdesign.printestimate",
                    ),
                ),
                (
                    "service_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="printdesign.printserviceitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Estimate Item",
                "verbose_name_plural": "Print Estimate Items",
                "ordering": ["sort_order"],
            },
        ),
    ]
